#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("strm_in_TDATA", 128, hls_in, 0, "axis", "in_data", 1),
	Port_Property("strm_in_TVALID", 1, hls_in, 3, "axis", "in_vld", 1),
	Port_Property("strm_in_TREADY", 1, hls_out, 3, "axis", "in_acc", 1),
	Port_Property("strm_in_TKEEP", 16, hls_in, 1, "axis", "in_data", 1),
	Port_Property("strm_in_TSTRB", 16, hls_in, 2, "axis", "in_data", 1),
	Port_Property("strm_in_TLAST", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("strm_out_TDATA", 128, hls_out, 4, "axis", "out_data", 1),
	Port_Property("strm_out_TVALID", 1, hls_out, 7, "axis", "out_vld", 1),
	Port_Property("strm_out_TREADY", 1, hls_in, 7, "axis", "out_acc", 1),
	Port_Property("strm_out_TKEEP", 16, hls_out, 5, "axis", "out_data", 1),
	Port_Property("strm_out_TSTRB", 16, hls_out, 6, "axis", "out_data", 1),
	Port_Property("strm_out_TLAST", 1, hls_out, 7, "axis", "out_data", 1),
	Port_Property("s_axi_BUS1_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_BUS1_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_BUS1_AWADDR", 6, hls_in, -1, "", "", 1),
	Port_Property("s_axi_BUS1_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_BUS1_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_BUS1_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_BUS1_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_BUS1_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_BUS1_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_BUS1_ARADDR", 6, hls_in, -1, "", "", 1),
	Port_Property("s_axi_BUS1_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_BUS1_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_BUS1_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_BUS1_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_BUS1_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_BUS1_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_BUS1_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "conv";
