-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv_conv_Pipeline_ReadWeightStreamsLOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    strm_in_TVALID : IN STD_LOGIC;
    sext_ln190 : IN STD_LOGIC_VECTOR (29 downto 0);
    totalWeightStreams : IN STD_LOGIC_VECTOR (31 downto 0);
    streamsPerFilter : IN STD_LOGIC_VECTOR (31 downto 0);
    filter_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_ce0 : OUT STD_LOGIC;
    filter_V_we0 : OUT STD_LOGIC;
    filter_V_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_ce1 : OUT STD_LOGIC;
    filter_V_we1 : OUT STD_LOGIC;
    filter_V_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_15_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_15_ce0 : OUT STD_LOGIC;
    filter_V_15_we0 : OUT STD_LOGIC;
    filter_V_15_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_15_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_15_ce1 : OUT STD_LOGIC;
    filter_V_15_we1 : OUT STD_LOGIC;
    filter_V_15_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_14_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_14_ce0 : OUT STD_LOGIC;
    filter_V_14_we0 : OUT STD_LOGIC;
    filter_V_14_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_14_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_14_ce1 : OUT STD_LOGIC;
    filter_V_14_we1 : OUT STD_LOGIC;
    filter_V_14_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_13_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_13_ce0 : OUT STD_LOGIC;
    filter_V_13_we0 : OUT STD_LOGIC;
    filter_V_13_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_13_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_13_ce1 : OUT STD_LOGIC;
    filter_V_13_we1 : OUT STD_LOGIC;
    filter_V_13_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_12_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_12_ce0 : OUT STD_LOGIC;
    filter_V_12_we0 : OUT STD_LOGIC;
    filter_V_12_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_12_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_12_ce1 : OUT STD_LOGIC;
    filter_V_12_we1 : OUT STD_LOGIC;
    filter_V_12_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_11_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_11_ce0 : OUT STD_LOGIC;
    filter_V_11_we0 : OUT STD_LOGIC;
    filter_V_11_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_11_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_11_ce1 : OUT STD_LOGIC;
    filter_V_11_we1 : OUT STD_LOGIC;
    filter_V_11_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_10_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_10_ce0 : OUT STD_LOGIC;
    filter_V_10_we0 : OUT STD_LOGIC;
    filter_V_10_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_10_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_10_ce1 : OUT STD_LOGIC;
    filter_V_10_we1 : OUT STD_LOGIC;
    filter_V_10_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_9_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_9_ce0 : OUT STD_LOGIC;
    filter_V_9_we0 : OUT STD_LOGIC;
    filter_V_9_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_9_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_9_ce1 : OUT STD_LOGIC;
    filter_V_9_we1 : OUT STD_LOGIC;
    filter_V_9_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_8_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_8_ce0 : OUT STD_LOGIC;
    filter_V_8_we0 : OUT STD_LOGIC;
    filter_V_8_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_8_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_8_ce1 : OUT STD_LOGIC;
    filter_V_8_we1 : OUT STD_LOGIC;
    filter_V_8_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_7_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_7_ce0 : OUT STD_LOGIC;
    filter_V_7_we0 : OUT STD_LOGIC;
    filter_V_7_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_7_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_7_ce1 : OUT STD_LOGIC;
    filter_V_7_we1 : OUT STD_LOGIC;
    filter_V_7_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_6_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_6_ce0 : OUT STD_LOGIC;
    filter_V_6_we0 : OUT STD_LOGIC;
    filter_V_6_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_6_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_6_ce1 : OUT STD_LOGIC;
    filter_V_6_we1 : OUT STD_LOGIC;
    filter_V_6_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_5_ce0 : OUT STD_LOGIC;
    filter_V_5_we0 : OUT STD_LOGIC;
    filter_V_5_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_5_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_5_ce1 : OUT STD_LOGIC;
    filter_V_5_we1 : OUT STD_LOGIC;
    filter_V_5_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_4_ce0 : OUT STD_LOGIC;
    filter_V_4_we0 : OUT STD_LOGIC;
    filter_V_4_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_4_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_4_ce1 : OUT STD_LOGIC;
    filter_V_4_we1 : OUT STD_LOGIC;
    filter_V_4_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_3_ce0 : OUT STD_LOGIC;
    filter_V_3_we0 : OUT STD_LOGIC;
    filter_V_3_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_3_ce1 : OUT STD_LOGIC;
    filter_V_3_we1 : OUT STD_LOGIC;
    filter_V_3_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_2_ce0 : OUT STD_LOGIC;
    filter_V_2_we0 : OUT STD_LOGIC;
    filter_V_2_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_2_ce1 : OUT STD_LOGIC;
    filter_V_2_we1 : OUT STD_LOGIC;
    filter_V_2_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_1_ce0 : OUT STD_LOGIC;
    filter_V_1_we0 : OUT STD_LOGIC;
    filter_V_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    filter_V_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    filter_V_1_ce1 : OUT STD_LOGIC;
    filter_V_1_we1 : OUT STD_LOGIC;
    filter_V_1_d1 : OUT STD_LOGIC_VECTOR (63 downto 0);
    strm_in_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    strm_in_TREADY : OUT STD_LOGIC;
    strm_in_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
    strm_in_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
    strm_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of conv_conv_Pipeline_ReadWeightStreamsLOOP is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln195_fu_625_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal strm_in_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln190_cast_fu_582_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln190_cast_reg_955 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln171_fu_706_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln171_1_fu_736_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln171_fu_726_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal perWeightCounter_fu_128 : STD_LOGIC_VECTOR (31 downto 0);
    signal perWeightCounter_2_fu_800_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal saveAddr_fu_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal addrOffset_5_fu_840_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal currPE_fu_136 : STD_LOGIC_VECTOR (31 downto 0);
    signal currPE_7_fu_848_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal addrOffset_fu_140 : STD_LOGIC_VECTOR (31 downto 0);
    signal addrOffset_4_fu_856_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal streamIter_fu_144 : STD_LOGIC_VECTOR (31 downto 0);
    signal streamIter_5_fu_864_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_fu_148 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_3_fu_630_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln628_fu_756_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_650_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln160_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal numIters_fu_666_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln195_fu_642_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln171_fu_730_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal perWeightCounter_1_fu_674_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln207_fu_794_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal streamIter_4_fu_788_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal currPE_5_fu_812_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln216_fu_818_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal saveAddr_4_fu_782_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln212_fu_807_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal saveAddr_5_fu_824_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal currPE_6_fu_832_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component conv_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component conv_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    addrOffset_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    addrOffset_fu_140 <= ap_const_lv32_0;
                elsif (((icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    addrOffset_fu_140 <= addrOffset_4_fu_856_p3;
                end if;
            end if; 
        end if;
    end process;

    currPE_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    currPE_fu_136 <= ap_const_lv32_0;
                elsif (((icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    currPE_fu_136 <= currPE_7_fu_848_p3;
                end if;
            end if; 
        end if;
    end process;

    i_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_148 <= ap_const_lv32_0;
                elsif (((icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_fu_148 <= i_3_fu_630_p2;
                end if;
            end if; 
        end if;
    end process;

    perWeightCounter_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    perWeightCounter_fu_128 <= sext_ln190_cast_fu_582_p1;
                elsif (((icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    perWeightCounter_fu_128 <= perWeightCounter_2_fu_800_p3;
                end if;
            end if; 
        end if;
    end process;

    saveAddr_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    saveAddr_fu_132 <= ap_const_lv32_0;
                elsif (((icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    saveAddr_fu_132 <= addrOffset_5_fu_840_p3;
                end if;
            end if; 
        end if;
    end process;

    streamIter_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    streamIter_fu_144 <= ap_const_lv32_0;
                elsif (((icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    streamIter_fu_144 <= streamIter_5_fu_864_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                sext_ln190_cast_reg_955 <= sext_ln190_cast_fu_582_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln171_fu_730_p2 <= std_logic_vector(unsigned(trunc_ln195_fu_642_p1) + unsigned(ap_const_lv10_1));
    addrOffset_4_fu_856_p3 <= 
        saveAddr_5_fu_824_p3 when (icmp_ln212_fu_807_p2(0) = '1') else 
        addrOffset_fu_140;
    addrOffset_5_fu_840_p3 <= 
        saveAddr_5_fu_824_p3 when (icmp_ln212_fu_807_p2(0) = '1') else 
        saveAddr_4_fu_782_p2;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, strm_in_TVALID, icmp_ln195_fu_625_p2)
    begin
                ap_block_pp0_stage0_11001 <= ((icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (strm_in_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, strm_in_TVALID, icmp_ln195_fu_625_p2)
    begin
                ap_block_pp0_stage0_subdone <= ((icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (strm_in_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(strm_in_TVALID, icmp_ln195_fu_625_p2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (strm_in_TVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln195_fu_625_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    currPE_5_fu_812_p2 <= std_logic_vector(unsigned(currPE_fu_136) + unsigned(ap_const_lv32_1));
    currPE_6_fu_832_p3 <= 
        ap_const_lv32_0 when (icmp_ln216_fu_818_p2(0) = '1') else 
        currPE_5_fu_812_p2;
    currPE_7_fu_848_p3 <= 
        currPE_6_fu_832_p3 when (icmp_ln212_fu_807_p2(0) = '1') else 
        currPE_fu_136;
    filter_V_10_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_10_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_10_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_10_ce0 <= ap_const_logic_1;
        else 
            filter_V_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_10_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_10_ce1 <= ap_const_logic_1;
        else 
            filter_V_10_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_10_d0 <= trunc_ln628_fu_756_p1;
    filter_V_10_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_10_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_A) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_10_we0 <= ap_const_logic_1;
        else 
            filter_V_10_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_10_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_A) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_10_we1 <= ap_const_logic_1;
        else 
            filter_V_10_we1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_11_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_11_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_11_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_11_ce0 <= ap_const_logic_1;
        else 
            filter_V_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_11_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_11_ce1 <= ap_const_logic_1;
        else 
            filter_V_11_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_11_d0 <= trunc_ln628_fu_756_p1;
    filter_V_11_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_11_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_B) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_11_we0 <= ap_const_logic_1;
        else 
            filter_V_11_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_11_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_B) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_11_we1 <= ap_const_logic_1;
        else 
            filter_V_11_we1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_12_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_12_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_12_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_12_ce0 <= ap_const_logic_1;
        else 
            filter_V_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_12_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_12_ce1 <= ap_const_logic_1;
        else 
            filter_V_12_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_12_d0 <= trunc_ln628_fu_756_p1;
    filter_V_12_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_12_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_C) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_12_we0 <= ap_const_logic_1;
        else 
            filter_V_12_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_12_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_C) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_12_we1 <= ap_const_logic_1;
        else 
            filter_V_12_we1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_13_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_13_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_13_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_13_ce0 <= ap_const_logic_1;
        else 
            filter_V_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_13_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_13_ce1 <= ap_const_logic_1;
        else 
            filter_V_13_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_13_d0 <= trunc_ln628_fu_756_p1;
    filter_V_13_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_13_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_D) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_13_we0 <= ap_const_logic_1;
        else 
            filter_V_13_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_13_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_D) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_13_we1 <= ap_const_logic_1;
        else 
            filter_V_13_we1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_14_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_14_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_14_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_14_ce0 <= ap_const_logic_1;
        else 
            filter_V_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_14_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_14_ce1 <= ap_const_logic_1;
        else 
            filter_V_14_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_14_d0 <= trunc_ln628_fu_756_p1;
    filter_V_14_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_14_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_E) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_14_we0 <= ap_const_logic_1;
        else 
            filter_V_14_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_14_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_E) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_14_we1 <= ap_const_logic_1;
        else 
            filter_V_14_we1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_15_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_15_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_15_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_15_ce0 <= ap_const_logic_1;
        else 
            filter_V_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_15_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_15_ce1 <= ap_const_logic_1;
        else 
            filter_V_15_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_15_d0 <= trunc_ln628_fu_756_p1;
    filter_V_15_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_15_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_F) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_15_we0 <= ap_const_logic_1;
        else 
            filter_V_15_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_15_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_F) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_15_we1 <= ap_const_logic_1;
        else 
            filter_V_15_we1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_1_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_1_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_1_ce0 <= ap_const_logic_1;
        else 
            filter_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_1_ce1 <= ap_const_logic_1;
        else 
            filter_V_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_1_d0 <= trunc_ln628_fu_756_p1;
    filter_V_1_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_1_we0 <= ap_const_logic_1;
        else 
            filter_V_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_1_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_1_we1 <= ap_const_logic_1;
        else 
            filter_V_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_2_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_2_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_2_ce0 <= ap_const_logic_1;
        else 
            filter_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_2_ce1 <= ap_const_logic_1;
        else 
            filter_V_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_2_d0 <= trunc_ln628_fu_756_p1;
    filter_V_2_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_2_we0 <= ap_const_logic_1;
        else 
            filter_V_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_2_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_2_we1 <= ap_const_logic_1;
        else 
            filter_V_2_we1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_3_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_3_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_3_ce0 <= ap_const_logic_1;
        else 
            filter_V_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_3_ce1 <= ap_const_logic_1;
        else 
            filter_V_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_3_d0 <= trunc_ln628_fu_756_p1;
    filter_V_3_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_3_we0 <= ap_const_logic_1;
        else 
            filter_V_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_3_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_3_we1 <= ap_const_logic_1;
        else 
            filter_V_3_we1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_4_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_4_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_4_ce0 <= ap_const_logic_1;
        else 
            filter_V_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_4_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_4_ce1 <= ap_const_logic_1;
        else 
            filter_V_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_4_d0 <= trunc_ln628_fu_756_p1;
    filter_V_4_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_4_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_4) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_4_we0 <= ap_const_logic_1;
        else 
            filter_V_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_4_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_4) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_4_we1 <= ap_const_logic_1;
        else 
            filter_V_4_we1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_5_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_5_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_5_ce0 <= ap_const_logic_1;
        else 
            filter_V_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_5_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_5_ce1 <= ap_const_logic_1;
        else 
            filter_V_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_5_d0 <= trunc_ln628_fu_756_p1;
    filter_V_5_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_5_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_5) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_5_we0 <= ap_const_logic_1;
        else 
            filter_V_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_5_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_5) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_5_we1 <= ap_const_logic_1;
        else 
            filter_V_5_we1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_6_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_6_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_6_ce0 <= ap_const_logic_1;
        else 
            filter_V_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_6_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_6_ce1 <= ap_const_logic_1;
        else 
            filter_V_6_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_6_d0 <= trunc_ln628_fu_756_p1;
    filter_V_6_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_6_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_6_we0 <= ap_const_logic_1;
        else 
            filter_V_6_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_6_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_6_we1 <= ap_const_logic_1;
        else 
            filter_V_6_we1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_7_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_7_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_7_ce0 <= ap_const_logic_1;
        else 
            filter_V_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_7_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_7_ce1 <= ap_const_logic_1;
        else 
            filter_V_7_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_7_d0 <= trunc_ln628_fu_756_p1;
    filter_V_7_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_7_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_7) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_7_we0 <= ap_const_logic_1;
        else 
            filter_V_7_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_7_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_7) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_7_we1 <= ap_const_logic_1;
        else 
            filter_V_7_we1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_8_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_8_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_8_ce0 <= ap_const_logic_1;
        else 
            filter_V_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_8_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_8_ce1 <= ap_const_logic_1;
        else 
            filter_V_8_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_8_d0 <= trunc_ln628_fu_756_p1;
    filter_V_8_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_8_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_8) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_8_we0 <= ap_const_logic_1;
        else 
            filter_V_8_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_8_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_8) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_8_we1 <= ap_const_logic_1;
        else 
            filter_V_8_we1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_9_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_9_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_9_ce0 <= ap_const_logic_1;
        else 
            filter_V_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_9_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_9_ce1 <= ap_const_logic_1;
        else 
            filter_V_9_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_9_d0 <= trunc_ln628_fu_756_p1;
    filter_V_9_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_9_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_9) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_9_we0 <= ap_const_logic_1;
        else 
            filter_V_9_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_9_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_9) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_9_we1 <= ap_const_logic_1;
        else 
            filter_V_9_we1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_address0 <= zext_ln171_1_fu_736_p1(10 - 1 downto 0);
    filter_V_address1 <= zext_ln171_fu_706_p1(10 - 1 downto 0);

    filter_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_ce0 <= ap_const_logic_1;
        else 
            filter_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_ce1 <= ap_const_logic_1;
        else 
            filter_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    filter_V_d0 <= trunc_ln628_fu_756_p1;
    filter_V_d1 <= strm_in_TDATA(127 downto 64);

    filter_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_we0 <= ap_const_logic_1;
        else 
            filter_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    filter_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001, trunc_ln171_fu_726_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (trunc_ln171_fu_726_p1 = ap_const_lv4_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            filter_V_we1 <= ap_const_logic_1;
        else 
            filter_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    i_3_fu_630_p2 <= std_logic_vector(unsigned(i_fu_148) + unsigned(ap_const_lv32_1));
    icmp_ln160_fu_660_p2 <= "1" when (signed(tmp_fu_650_p4) < signed(ap_const_lv31_1)) else "0";
    icmp_ln195_fu_625_p2 <= "1" when (i_fu_148 = totalWeightStreams) else "0";
    icmp_ln207_fu_794_p2 <= "1" when (signed(perWeightCounter_1_fu_674_p2) < signed(ap_const_lv32_1)) else "0";
    icmp_ln212_fu_807_p2 <= "1" when (streamIter_4_fu_788_p2 = streamsPerFilter) else "0";
    icmp_ln216_fu_818_p2 <= "1" when (currPE_5_fu_812_p2 = ap_const_lv32_10) else "0";
    numIters_fu_666_p3 <= 
        perWeightCounter_fu_128 when (icmp_ln160_fu_660_p2(0) = '1') else 
        ap_const_lv32_2;
    perWeightCounter_1_fu_674_p2 <= std_logic_vector(unsigned(perWeightCounter_fu_128) - unsigned(numIters_fu_666_p3));
    perWeightCounter_2_fu_800_p3 <= 
        sext_ln190_cast_reg_955 when (icmp_ln207_fu_794_p2(0) = '1') else 
        perWeightCounter_1_fu_674_p2;
    saveAddr_4_fu_782_p2 <= std_logic_vector(unsigned(numIters_fu_666_p3) + unsigned(saveAddr_fu_132));
    saveAddr_5_fu_824_p3 <= 
        saveAddr_4_fu_782_p2 when (icmp_ln216_fu_818_p2(0) = '1') else 
        addrOffset_fu_140;
        sext_ln190_cast_fu_582_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln190),32));

    streamIter_4_fu_788_p2 <= std_logic_vector(unsigned(streamIter_fu_144) + unsigned(ap_const_lv32_1));
    streamIter_5_fu_864_p3 <= 
        ap_const_lv32_0 when (icmp_ln212_fu_807_p2(0) = '1') else 
        streamIter_4_fu_788_p2;

    strm_in_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, strm_in_TVALID, icmp_ln195_fu_625_p2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            strm_in_TDATA_blk_n <= strm_in_TVALID;
        else 
            strm_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    strm_in_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln195_fu_625_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln195_fu_625_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            strm_in_TREADY <= ap_const_logic_1;
        else 
            strm_in_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_650_p4 <= perWeightCounter_fu_128(31 downto 1);
    trunc_ln171_fu_726_p1 <= currPE_fu_136(4 - 1 downto 0);
    trunc_ln195_fu_642_p1 <= saveAddr_fu_132(10 - 1 downto 0);
    trunc_ln628_fu_756_p1 <= strm_in_TDATA(64 - 1 downto 0);
    zext_ln171_1_fu_736_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln171_fu_730_p2),64));
    zext_ln171_fu_706_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(saveAddr_fu_132),64));
end behav;
