# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pferreira/HwSw/Vivado/zcu104_mixed-conv_debug/zcu104_mixed-conv_debug.srcs/sources_1/bd/system/ip/system_conv_0_1/system_conv_0_1.xci
# IP: The module: 'system_conv_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pferreira/HwSw/Vivado/zcu104_mixed-conv_debug/zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/constraints/conv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_conv_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/pferreira/HwSw/Vivado/zcu104_mixed-conv_debug/zcu104_mixed-conv_debug.srcs/sources_1/bd/system/ip/system_conv_0_1/system_conv_0_1.xci
# IP: The module: 'system_conv_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pferreira/HwSw/Vivado/zcu104_mixed-conv_debug/zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/constraints/conv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_conv_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
