// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_conv_Pipeline_ReadBiasStreamsLOOP_VITIS_LOOP_240_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        strm_in_TVALID,
        zext_ln276,
        zext_ln239,
        bias_V_15_address0,
        bias_V_15_ce0,
        bias_V_15_we0,
        bias_V_15_d0,
        bias_V_14_address0,
        bias_V_14_ce0,
        bias_V_14_we0,
        bias_V_14_d0,
        bias_V_13_address0,
        bias_V_13_ce0,
        bias_V_13_we0,
        bias_V_13_d0,
        bias_V_12_address0,
        bias_V_12_ce0,
        bias_V_12_we0,
        bias_V_12_d0,
        bias_V_11_address0,
        bias_V_11_ce0,
        bias_V_11_we0,
        bias_V_11_d0,
        bias_V_10_address0,
        bias_V_10_ce0,
        bias_V_10_we0,
        bias_V_10_d0,
        bias_V_9_address0,
        bias_V_9_ce0,
        bias_V_9_we0,
        bias_V_9_d0,
        bias_V_8_address0,
        bias_V_8_ce0,
        bias_V_8_we0,
        bias_V_8_d0,
        bias_V_7_address0,
        bias_V_7_ce0,
        bias_V_7_we0,
        bias_V_7_d0,
        bias_V_6_address0,
        bias_V_6_ce0,
        bias_V_6_we0,
        bias_V_6_d0,
        bias_V_5_address0,
        bias_V_5_ce0,
        bias_V_5_we0,
        bias_V_5_d0,
        bias_V_4_address0,
        bias_V_4_ce0,
        bias_V_4_we0,
        bias_V_4_d0,
        bias_V_3_address0,
        bias_V_3_ce0,
        bias_V_3_we0,
        bias_V_3_d0,
        bias_V_2_address0,
        bias_V_2_ce0,
        bias_V_2_we0,
        bias_V_2_d0,
        bias_V_1_address0,
        bias_V_1_ce0,
        bias_V_1_we0,
        bias_V_1_d0,
        bias_V_address0,
        bias_V_ce0,
        bias_V_we0,
        bias_V_d0,
        strm_in_TDATA,
        strm_in_TREADY,
        strm_in_TKEEP,
        strm_in_TSTRB,
        strm_in_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   strm_in_TVALID;
input  [36:0] zext_ln276;
input  [29:0] zext_ln239;
output  [2:0] bias_V_15_address0;
output   bias_V_15_ce0;
output   bias_V_15_we0;
output  [7:0] bias_V_15_d0;
output  [2:0] bias_V_14_address0;
output   bias_V_14_ce0;
output   bias_V_14_we0;
output  [7:0] bias_V_14_d0;
output  [2:0] bias_V_13_address0;
output   bias_V_13_ce0;
output   bias_V_13_we0;
output  [7:0] bias_V_13_d0;
output  [2:0] bias_V_12_address0;
output   bias_V_12_ce0;
output   bias_V_12_we0;
output  [7:0] bias_V_12_d0;
output  [2:0] bias_V_11_address0;
output   bias_V_11_ce0;
output   bias_V_11_we0;
output  [7:0] bias_V_11_d0;
output  [2:0] bias_V_10_address0;
output   bias_V_10_ce0;
output   bias_V_10_we0;
output  [7:0] bias_V_10_d0;
output  [2:0] bias_V_9_address0;
output   bias_V_9_ce0;
output   bias_V_9_we0;
output  [7:0] bias_V_9_d0;
output  [2:0] bias_V_8_address0;
output   bias_V_8_ce0;
output   bias_V_8_we0;
output  [7:0] bias_V_8_d0;
output  [2:0] bias_V_7_address0;
output   bias_V_7_ce0;
output   bias_V_7_we0;
output  [7:0] bias_V_7_d0;
output  [2:0] bias_V_6_address0;
output   bias_V_6_ce0;
output   bias_V_6_we0;
output  [7:0] bias_V_6_d0;
output  [2:0] bias_V_5_address0;
output   bias_V_5_ce0;
output   bias_V_5_we0;
output  [7:0] bias_V_5_d0;
output  [2:0] bias_V_4_address0;
output   bias_V_4_ce0;
output   bias_V_4_we0;
output  [7:0] bias_V_4_d0;
output  [2:0] bias_V_3_address0;
output   bias_V_3_ce0;
output   bias_V_3_we0;
output  [7:0] bias_V_3_d0;
output  [2:0] bias_V_2_address0;
output   bias_V_2_ce0;
output   bias_V_2_we0;
output  [7:0] bias_V_2_d0;
output  [2:0] bias_V_1_address0;
output   bias_V_1_ce0;
output   bias_V_1_we0;
output  [7:0] bias_V_1_d0;
output  [2:0] bias_V_address0;
output   bias_V_ce0;
output   bias_V_we0;
output  [7:0] bias_V_d0;
input  [127:0] strm_in_TDATA;
output   strm_in_TREADY;
input  [15:0] strm_in_TKEEP;
input  [15:0] strm_in_TSTRB;
input  [0:0] strm_in_TLAST;

reg ap_idle;
reg bias_V_15_ce0;
reg bias_V_15_we0;
reg bias_V_14_ce0;
reg bias_V_14_we0;
reg bias_V_13_ce0;
reg bias_V_13_we0;
reg bias_V_12_ce0;
reg bias_V_12_we0;
reg bias_V_11_ce0;
reg bias_V_11_we0;
reg bias_V_10_ce0;
reg bias_V_10_we0;
reg bias_V_9_ce0;
reg bias_V_9_we0;
reg bias_V_8_ce0;
reg bias_V_8_we0;
reg bias_V_7_ce0;
reg bias_V_7_we0;
reg bias_V_6_ce0;
reg bias_V_6_we0;
reg bias_V_5_ce0;
reg bias_V_5_we0;
reg bias_V_4_ce0;
reg bias_V_4_we0;
reg bias_V_3_ce0;
reg bias_V_3_we0;
reg bias_V_2_ce0;
reg bias_V_2_we0;
reg bias_V_1_ce0;
reg bias_V_1_we0;
reg bias_V_ce0;
reg bias_V_we0;
reg strm_in_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln239_fu_416_p2;
wire   [0:0] select_ln232_1_fu_463_p3;
wire   [0:0] icmp_ln243_fu_479_p2;
reg    ap_predicate_op42_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    strm_in_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire  signed [67:0] zext_ln276_cast_fu_386_p1;
reg  signed [67:0] zext_ln276_cast_reg_678;
wire   [63:0] zext_ln239_cast_cast_fu_394_p1;
reg   [63:0] zext_ln239_cast_cast_reg_683;
reg   [0:0] select_ln232_1_reg_692;
wire   [63:0] select_ln239_fu_471_p3;
reg   [63:0] select_ln239_reg_696;
wire   [3:0] trunc_ln246_fu_494_p1;
reg   [3:0] trunc_ln246_reg_719;
reg   [4:0] j_fu_138;
wire   [4:0] j_1_fu_498_p2;
wire    ap_loop_init;
reg   [63:0] i_1_fu_142;
reg   [67:0] indvar_flatten_fu_146;
wire   [67:0] add_ln239_fu_421_p2;
reg   [127:0] tmp_data_V_fu_150;
wire   [7:0] trunc_ln358_fu_631_p1;
wire  signed [31:0] zext_ln239_cast_fu_390_p1;
wire   [0:0] icmp_ln240_fu_433_p2;
wire   [63:0] add_ln239_1_fu_447_p2;
wire   [0:0] cmp6_i2921_mid1_fu_453_p2;
wire   [0:0] cmp6_i29211305_fu_458_p2;
wire   [4:0] select_ln232_fu_439_p3;
wire   [6:0] shl_ln1_fu_522_p3;
wire   [6:0] sub_ln247_fu_529_p2;
wire   [6:0] xor_ln628_fu_535_p2;
wire   [0:0] icmp_ln628_fu_541_p2;
wire   [6:0] sub_ln628_fu_557_p2;
wire   [6:0] sub_ln628_1_fu_569_p2;
reg   [127:0] tmp_fu_547_p4;
wire   [6:0] or_ln628_fu_563_p2;
wire   [6:0] select_ln628_fu_575_p3;
wire   [6:0] select_ln628_2_fu_591_p3;
wire   [6:0] xor_ln628_1_fu_599_p2;
wire   [127:0] select_ln628_1_fu_583_p3;
wire   [127:0] zext_ln628_fu_605_p1;
wire   [127:0] zext_ln628_1_fu_609_p1;
wire   [127:0] lshr_ln628_fu_613_p2;
wire   [127:0] lshr_ln628_1_fu_619_p2;
wire   [127:0] p_Result_s_fu_625_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

conv_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_1_fu_142 <= 64'd0;
        end else if (((icmp_ln239_fu_416_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_1_fu_142 <= select_ln239_fu_471_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_146 <= 68'd0;
        end else if (((icmp_ln239_fu_416_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_146 <= add_ln239_fu_421_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_138 <= 5'd0;
        end else if (((icmp_ln239_fu_416_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            j_fu_138 <= j_1_fu_498_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln239_fu_416_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln232_1_reg_692 <= select_ln232_1_fu_463_p3;
        select_ln239_reg_696 <= select_ln239_fu_471_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln243_fu_479_p2 == 1'd1) & (select_ln232_1_fu_463_p3 == 1'd1) & (icmp_ln239_fu_416_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_data_V_fu_150 <= strm_in_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (select_ln232_1_fu_463_p3 == 1'd1) & (icmp_ln239_fu_416_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln246_reg_719 <= trunc_ln246_fu_494_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln239_cast_cast_reg_683[31 : 0] <= zext_ln239_cast_cast_fu_394_p1[31 : 0];
        zext_ln276_cast_reg_678 <= zext_ln276_cast_fu_386_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln239_fu_416_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_10_ce0 = 1'b1;
    end else begin
        bias_V_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd10) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_10_we0 = 1'b1;
    end else begin
        bias_V_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_11_ce0 = 1'b1;
    end else begin
        bias_V_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd11) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_11_we0 = 1'b1;
    end else begin
        bias_V_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_12_ce0 = 1'b1;
    end else begin
        bias_V_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd12) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_12_we0 = 1'b1;
    end else begin
        bias_V_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_13_ce0 = 1'b1;
    end else begin
        bias_V_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd13) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_13_we0 = 1'b1;
    end else begin
        bias_V_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_14_ce0 = 1'b1;
    end else begin
        bias_V_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd14) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_14_we0 = 1'b1;
    end else begin
        bias_V_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_15_ce0 = 1'b1;
    end else begin
        bias_V_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd15) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_15_we0 = 1'b1;
    end else begin
        bias_V_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_1_ce0 = 1'b1;
    end else begin
        bias_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd1) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_1_we0 = 1'b1;
    end else begin
        bias_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_2_ce0 = 1'b1;
    end else begin
        bias_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd2) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_2_we0 = 1'b1;
    end else begin
        bias_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_3_ce0 = 1'b1;
    end else begin
        bias_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd3) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_3_we0 = 1'b1;
    end else begin
        bias_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_4_ce0 = 1'b1;
    end else begin
        bias_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd4) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_4_we0 = 1'b1;
    end else begin
        bias_V_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_5_ce0 = 1'b1;
    end else begin
        bias_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd5) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_5_we0 = 1'b1;
    end else begin
        bias_V_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_6_ce0 = 1'b1;
    end else begin
        bias_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd6) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_6_we0 = 1'b1;
    end else begin
        bias_V_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_7_ce0 = 1'b1;
    end else begin
        bias_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd7) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_7_we0 = 1'b1;
    end else begin
        bias_V_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_8_ce0 = 1'b1;
    end else begin
        bias_V_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd8) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_8_we0 = 1'b1;
    end else begin
        bias_V_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_9_ce0 = 1'b1;
    end else begin
        bias_V_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd9) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_9_we0 = 1'b1;
    end else begin
        bias_V_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bias_V_ce0 = 1'b1;
    end else begin
        bias_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln246_reg_719 == 4'd0) & (select_ln232_1_reg_692 == 1'd1))) begin
        bias_V_we0 = 1'b1;
    end else begin
        bias_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op42_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        strm_in_TDATA_blk_n = strm_in_TVALID;
    end else begin
        strm_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op42_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        strm_in_TREADY = 1'b1;
    end else begin
        strm_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln239_1_fu_447_p2 = (i_1_fu_142 + 64'd1);

assign add_ln239_fu_421_p2 = (indvar_flatten_fu_146 + 68'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_predicate_op42_read_state2 == 1'b1) & (strm_in_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_predicate_op42_read_state2 == 1'b1) & (strm_in_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op42_read_state2 == 1'b1) & (strm_in_TVALID == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

always @ (*) begin
    ap_predicate_op42_read_state2 = ((icmp_ln243_fu_479_p2 == 1'd1) & (select_ln232_1_fu_463_p3 == 1'd1) & (icmp_ln239_fu_416_p2 == 1'd0));
end

assign bias_V_10_address0 = select_ln239_reg_696;

assign bias_V_10_d0 = trunc_ln358_fu_631_p1;

assign bias_V_11_address0 = select_ln239_reg_696;

assign bias_V_11_d0 = trunc_ln358_fu_631_p1;

assign bias_V_12_address0 = select_ln239_reg_696;

assign bias_V_12_d0 = trunc_ln358_fu_631_p1;

assign bias_V_13_address0 = select_ln239_reg_696;

assign bias_V_13_d0 = trunc_ln358_fu_631_p1;

assign bias_V_14_address0 = select_ln239_reg_696;

assign bias_V_14_d0 = trunc_ln358_fu_631_p1;

assign bias_V_15_address0 = select_ln239_reg_696;

assign bias_V_15_d0 = trunc_ln358_fu_631_p1;

assign bias_V_1_address0 = select_ln239_reg_696;

assign bias_V_1_d0 = trunc_ln358_fu_631_p1;

assign bias_V_2_address0 = select_ln239_reg_696;

assign bias_V_2_d0 = trunc_ln358_fu_631_p1;

assign bias_V_3_address0 = select_ln239_reg_696;

assign bias_V_3_d0 = trunc_ln358_fu_631_p1;

assign bias_V_4_address0 = select_ln239_reg_696;

assign bias_V_4_d0 = trunc_ln358_fu_631_p1;

assign bias_V_5_address0 = select_ln239_reg_696;

assign bias_V_5_d0 = trunc_ln358_fu_631_p1;

assign bias_V_6_address0 = select_ln239_reg_696;

assign bias_V_6_d0 = trunc_ln358_fu_631_p1;

assign bias_V_7_address0 = select_ln239_reg_696;

assign bias_V_7_d0 = trunc_ln358_fu_631_p1;

assign bias_V_8_address0 = select_ln239_reg_696;

assign bias_V_8_d0 = trunc_ln358_fu_631_p1;

assign bias_V_9_address0 = select_ln239_reg_696;

assign bias_V_9_d0 = trunc_ln358_fu_631_p1;

assign bias_V_address0 = select_ln239_reg_696;

assign bias_V_d0 = trunc_ln358_fu_631_p1;

assign cmp6_i29211305_fu_458_p2 = ((i_1_fu_142 < zext_ln239_cast_cast_reg_683) ? 1'b1 : 1'b0);

assign cmp6_i2921_mid1_fu_453_p2 = ((add_ln239_1_fu_447_p2 < zext_ln239_cast_cast_reg_683) ? 1'b1 : 1'b0);

assign icmp_ln239_fu_416_p2 = ((indvar_flatten_fu_146 == zext_ln276_cast_reg_678) ? 1'b1 : 1'b0);

assign icmp_ln240_fu_433_p2 = ((j_fu_138 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln243_fu_479_p2 = ((select_ln232_fu_439_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln628_fu_541_p2 = ((sub_ln247_fu_529_p2 > xor_ln628_fu_535_p2) ? 1'b1 : 1'b0);

assign j_1_fu_498_p2 = (select_ln232_fu_439_p3 + 5'd1);

assign lshr_ln628_1_fu_619_p2 = 128'd340282366920938463463374607431768211455 >> zext_ln628_1_fu_609_p1;

assign lshr_ln628_fu_613_p2 = select_ln628_1_fu_583_p3 >> zext_ln628_fu_605_p1;

assign or_ln628_fu_563_p2 = (shl_ln1_fu_522_p3 | 7'd7);

assign p_Result_s_fu_625_p2 = (lshr_ln628_fu_613_p2 & lshr_ln628_1_fu_619_p2);

assign select_ln232_1_fu_463_p3 = ((icmp_ln240_fu_433_p2[0:0] == 1'b1) ? cmp6_i2921_mid1_fu_453_p2 : cmp6_i29211305_fu_458_p2);

assign select_ln232_fu_439_p3 = ((icmp_ln240_fu_433_p2[0:0] == 1'b1) ? 5'd0 : j_fu_138);

assign select_ln239_fu_471_p3 = ((icmp_ln240_fu_433_p2[0:0] == 1'b1) ? add_ln239_1_fu_447_p2 : i_1_fu_142);

assign select_ln628_1_fu_583_p3 = ((icmp_ln628_fu_541_p2[0:0] == 1'b1) ? tmp_fu_547_p4 : tmp_data_V_fu_150);

assign select_ln628_2_fu_591_p3 = ((icmp_ln628_fu_541_p2[0:0] == 1'b1) ? or_ln628_fu_563_p2 : sub_ln247_fu_529_p2);

assign select_ln628_fu_575_p3 = ((icmp_ln628_fu_541_p2[0:0] == 1'b1) ? sub_ln628_fu_557_p2 : sub_ln628_1_fu_569_p2);

assign shl_ln1_fu_522_p3 = {{trunc_ln246_reg_719}, {3'd0}};

assign sub_ln247_fu_529_p2 = ($signed(7'd120) - $signed(shl_ln1_fu_522_p3));

assign sub_ln628_1_fu_569_p2 = (xor_ln628_fu_535_p2 - sub_ln247_fu_529_p2);

assign sub_ln628_fu_557_p2 = (sub_ln247_fu_529_p2 - xor_ln628_fu_535_p2);

integer ap_tvar_int_0;

always @ (tmp_data_V_fu_150) begin
    for (ap_tvar_int_0 = 128 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 127 - 0) begin
            tmp_fu_547_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_fu_547_p4[ap_tvar_int_0] = tmp_data_V_fu_150[127 - ap_tvar_int_0];
        end
    end
end

assign trunc_ln246_fu_494_p1 = select_ln232_fu_439_p3[3:0];

assign trunc_ln358_fu_631_p1 = p_Result_s_fu_625_p2[7:0];

assign xor_ln628_1_fu_599_p2 = (select_ln628_fu_575_p3 ^ 7'd127);

assign xor_ln628_fu_535_p2 = (shl_ln1_fu_522_p3 ^ 7'd127);

assign zext_ln239_cast_cast_fu_394_p1 = $unsigned(zext_ln239_cast_fu_390_p1);

assign zext_ln239_cast_fu_390_p1 = $signed(zext_ln239);

assign zext_ln276_cast_fu_386_p1 = $signed(zext_ln276);

assign zext_ln628_1_fu_609_p1 = xor_ln628_1_fu_599_p2;

assign zext_ln628_fu_605_p1 = select_ln628_2_fu_591_p3;

always @ (posedge ap_clk) begin
    zext_ln239_cast_cast_reg_683[63:32] <= 32'b00000000000000000000000000000000;
end

endmodule //conv_conv_Pipeline_ReadBiasStreamsLOOP_VITIS_LOOP_240_1
