#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Apr 18 03:01:47 WEST 2024
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# Tool Version Limit: 2022.10 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64 "

# Set vhdlan compile options
vhdlan_opts="-full64 "

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log "

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_13 zynq_ultra_ps_e_vip_v1_0_13 xil_defaultlib lib_pkg_v1_0_2 fifo_generator_v13_2_7 lib_fifo_v1_0_16 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_29 axi_sg_v4_1_15 axi_dma_v7_1_28 xlconstant_v1_1_7 proc_sys_reset_v5_0_13 smartconnect_v1_0 axi_register_slice_v2_1_27 generic_baseblocks_v2_1_0 axi_data_fifo_v2_1_26 axi_crossbar_v2_1_28 axi_protocol_converter_v2_1_27 axi_clock_converter_v2_1_26 blk_mem_gen_v8_4_5 axi_dwidth_converter_v2_1_27)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2022.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "/home/mpv/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/home/mpv/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/home/mpv/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/home/mpv/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ffc2/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_zynq_ultra_ps_e_0_0/sim/system_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_16 $vhdlan_opts \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/6c82/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_29 $vhdlan_opts \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/2237/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_15 $vhdlan_opts \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/751a/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_28 $vhdlan_opts \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/70c4/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_dma_0_0/sim/system_axi_dma_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_dma_w2_0/sim/system_axi_dma_w2_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/sim/bd_919a.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/badb/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_919a_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_919a_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_919a_arsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_919a_rsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_919a_awsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_919a_wsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_919a_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/be1f/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_919a_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_919a_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/637d/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_919a_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f38e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_919a_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_919a_sarn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_919a_srn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_919a_s01mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_919a_s01tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_919a_s01sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_919a_s01a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_919a_sawn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_919a_swn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_919a_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/9cc5/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_919a_m00s2a_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_919a_m00arn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_919a_m00rn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_919a_m00awn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_919a_m00wn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_919a_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/6bba/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_919a_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_0/sim/system_smartconnect_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/sim/bd_515b.v" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_0/sim/bd_515b_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_1/sim/bd_515b_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_2/sim/bd_515b_arsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_3/sim/bd_515b_rsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_4/sim/bd_515b_awsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_5/sim/bd_515b_wsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_6/sim/bd_515b_bsw_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_7/sim/bd_515b_s00mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_8/sim/bd_515b_s00tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_9/sim/bd_515b_s00sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_10/sim/bd_515b_s00a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_11/sim/bd_515b_sarn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_12/sim/bd_515b_srn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_13/sim/bd_515b_s01mmu_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_14/sim/bd_515b_s01tr_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_15/sim/bd_515b_s01sic_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_16/sim/bd_515b_s01a2s_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_17/sim/bd_515b_sawn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_18/sim/bd_515b_swn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_19/sim/bd_515b_sbn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_20/sim/bd_515b_m00s2a_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_21/sim/bd_515b_m00arn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_22/sim/bd_515b_m00rn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_23/sim/bd_515b_m00awn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_24/sim/bd_515b_m00wn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_25/sim/bd_515b_m00bn_0.sv" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/bd_0/ip/ip_26/sim/bd_515b_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_smartconnect_0_1/sim/system_smartconnect_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_rst_ps8_0_100M_0/sim/system_rst_ps8_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/3111/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_28 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/c40e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_bias_V_RAM_AUTO_1R1W.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_BUS1_s_axi.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_conv_Pipeline_OutYLOOP_FilterLOOP_KernelXLOOP_ChannelLOOP.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_conv_Pipeline_ReadActivationsLOOP.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_conv_Pipeline_ReadBiasStreamsLOOP_VITIS_LOOP_240_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_conv_Pipeline_ReadWeightStreamsLOOP.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_conv_Pipeline_VITIS_LOOP_330_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_filter_V_RAM_AUTO_1R1W.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_flow_control_loop_pipe_sequential_init.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_inputMap_V_RAM_AUTO_1R1W.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mac_muladd_8ns_4s_12s_13_4_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mac_muladd_8ns_4s_13s_14_4_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mac_muladd_8ns_4s_32s_32_4_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mac_muladd_9s_4s_13s_14_4_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mac_muladd_9s_4s_14s_14_4_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mac_muladd_9s_4s_32s_32_4_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_3ns_3ns_6_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_3ns_28ns_31_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_3ns_30s_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_3ns_31ns_34_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_6ns_29s_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_8ns_4s_12_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_9s_4s_13_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_10ns_2ns_12_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_10ns_3ns_13_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_10ns_34ns_44_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_10ns_44ns_54_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_10ns_54ns_64_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_13ns_3ns_16_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_16ns_30s_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_30s_3ns_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_30s_32s_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_32ns_2ns_34_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_32s_2ns_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mul_32s_32s_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_mux_53_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_regslice_both.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_sdiv_33ns_3ns_10_37_seq_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv_urem_12ns_4ns_4_16_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/876f/hdl/vhdl/conv.vhd" \
    "$ref_dir/../../../bd/system/ip/system_conv_0_1/sim/system_conv_0_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_bias_V_RAM_AUTO_1R1W.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_BUS1_s_axi.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_conv_w2_Pipeline_OutYLOOP_FilterLOOP_KernelXLOOP_ChannelLOOP.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_conv_w2_Pipeline_ReadActivationsLOOP.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_conv_w2_Pipeline_ReadBiasStreamsLOOP_VITIS_LOOP_240_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_conv_w2_Pipeline_ReadWeightStreamsLOOP.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_conv_w2_Pipeline_VITIS_LOOP_330_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_filter_V_RAM_AUTO_1R1W.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_flow_control_loop_pipe_sequential_init.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_inputMap_V_RAM_AUTO_1R1W.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mac_muladd_8ns_2s_10s_11_4_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mac_muladd_8ns_2s_11s_12_4_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mac_muladd_8ns_2s_32s_32_4_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mac_muladd_9s_2s_11s_12_4_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mac_muladd_9s_2s_12s_12_4_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mac_muladd_9s_2s_32s_32_4_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_3ns_3ns_6_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_3ns_28ns_31_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_3ns_30s_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_3ns_31ns_34_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_8ns_2s_10_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_9s_2s_11_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_10ns_2ns_12_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_10ns_3ns_13_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_10ns_34ns_44_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_10ns_44ns_54_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_10ns_54ns_64_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_13ns_3ns_16_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_16ns_30s_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_30s_3ns_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_30s_32s_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_32ns_2ns_34_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_32s_2ns_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_32s_32s_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mul_mul_6ns_28s_32_4_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mux_42_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_mux_53_32_1_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_regslice_both.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_sdiv_33ns_3ns_10_37_seq_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2_urem_12ns_4ns_4_16_1.vhd" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/eea8/hdl/vhdl/conv_w2.vhd" \
    "$ref_dir/../../../bd/system/ip/system_conv_w2_0_0/sim/system_conv_w2_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/aeb3/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/b8be/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/25a8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/4675/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/abef/hdl" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_0_1/drivers/conv_v1_7/src" +incdir+"$ref_dir/../../../../zcu104_mixed-conv_debug.gen/sources_1/bd/system/ip/system_conv_w2_0_0/drivers/conv_w2_v1_7/src" +incdir+"/home/mpv/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_auto_ds_0/sim/system_auto_ds_0.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/sim/system.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/pferreira/HwSw/Vivado/zcu104_mixed-conv_debug/zcu104_mixed-conv_debug.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
