
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xconv.h"

/*
* The configuration table for devices
*/

XConv_Config XConv_ConfigTable[XPAR_XCONV_NUM_INSTANCES] =
{
	{
		XPAR_CONV_0_DEVICE_ID,
		XPAR_CONV_0_S_AXI_BUS1_BASEADDR
	}
};


